paths:
    /api/products/:
      get:
        summary: Get all products
        tags:
          - Products
        reponses:
          "200":
            description: The products were obtained correctly
            content:
              aplication/json:
                schema:
                  type: array
                  items: 
                    $ref: "#components/schemas/Product"
          "500":
            description: Error on the server when you get the products
      post:
        summary: Add a product
        tags:
          - Products
        requestBody:
          required: true
          content:
            aplication/json:
              schema:
                $ref: "#components/requestBodies/Product"
        reponses:
          "200":
            description: Product added correctly
            content:
              aplication/json:
                schema:
                  type: array
                  items: 
                    $ref: "#components/schemas/Product"
          "500":
            description: Error on the server when you add the product
    /api/products/many:
      post:
        summary: Add a products
        tags:
          - Products
        requestBody:
          required: true
          content:
            aplication/json:
              schema:
                $ref: "#components/requestBodies/Product"
        reponses:
          "200":
            description: Products added correctly
            content:
              aplication/json:
                schema:
                  type: array
                  items: 
                    $ref: "#components/schemas/Product"
          "500":
            description: Error on the server when you add the products
    /api/products/{pid}:
      get:
        summary: Get the product by id
        tags:
          - Products
        parameters:
        - name: pid
          in: path
          required: true
          description: id of product to find
          schema:
            $type: String
        reponses:
          "200":
            description: Product find correctly
            content:
              aplication/json:
                schema:
                  type: array
                  items: 
                    $ref: "#components/schemas/Product"
          "500":
            description: Error in server when you look for the product
      put:
        summary: Update a product
        tags:
          - Products
        parameters:
        - name: pid
          in: path
          required: true
          description: id of product to find
          schema:
            $type: String
        requestBody:
          required: true
          content:
            aplication/json:
              schema:
                $ref: "#components/requestBodies/Product"
        reponses:
          "200":
            description: Product modified correctly
            content:
              aplication/json:
                schema:
                  type: array
                  items: 
                    $ref: "#components/schemas/Product"
          "500":
            description: Error on the server when you modified the product
      delete:
        summary: Delete a product
        tags:
          - Products
        parameters:
        - name: pid
          in: path
          required: true
          description: id of product to find
          schema:
            $type: String
        reponses:
          "200":
            description: product disposed correctly
            content:
              aplication/json:
                schema:
                  type: array
                  items: 
                    $ref: "#components/schemas/Product"
          "500":
            description: Error on the server when you delete the product
    /api/products/mock/mockingproducts:
      get:
        summary: You get a product mockup
        tags:
          - Products
        reponses:
          "200":
            description: You get the mock correctly
            content:
              aplication/json:
                schema:
                  type: array
                  items: 
                    $ref: "#components/schemas/Product"
          "500":
            description: Error on the server when you get the products


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: mongo autogenerated id
        title:
          type: String
          description: Product name
        description:
          type: String
          description: description of product
        code:
          type: String
          description: unique code of product
        price:
          type: Number
          description: price of product
        stock:
          type: Number
          description: stock of product
        category:
          type: String
          description: category of product
        thumbnails:
          type: Array
          description: collection of images
        owner:
          type: String
          description: email of creator
      example:
        _id: ObjectId("655d3c1817276038ecb5881c")
        title: "Mana"
        description: "Galletitas"
        code: "AXAZZAX2-AZFR"
        price: 1.1
        stock: 46
        category: "Comestibles"
        thumbnails: Array (2)
        owner: "ejemploOwner@yopmail.com"
  requestBodies:
    Product:
      type: object
      properties:
        title:
          type: String
          description: Product name
        description:
          type: String
          description: description of product
        code:
          type: String
          description: unique code of product
        price:
          type: Number
          description: price of product
        stock:
          type: Number
          description: stock of product
        category:
          type: String
          description: category of product
        thumbnails:
          type: Array
          description: collection of images
      example:
        title: "Mana"
        description: "Galletitas"
        code: "AXAZZAX2-AZFR"
        price: 1.1
        stock: 46
        category: "Comestibles"
        thumbnails: Array (2)